name: Build/release

on: push


jobs:
  release:
    runs-on: ${{ matrix.os }}    
    env:
      DEBUG: electron-builder
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install
      - name: Build web app and prepare Electron app
        run: npm run build:web && node prepareElectronApp.js

      - name: Build and release Electron app (macOS)
        if: matrix.os == 'macos-latest'
        run: npm exec electron-builder -- --mac --publish always
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Build and release Electron app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm exec electron-builder -- --linux --publish always
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Build and release Electron app (Windows)
        if: matrix.os == 'windows-latest'
        run: npm exec electron-builder -- --win --publish always
        env:
          GH_TOKEN: ${{ secrets.github_token }}